cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED AOWIS_COVERAGE_BINARY_DIR OR "${AOWIS_COVERAGE_BINARY_DIR}" STREQUAL "")
    message(FATAL_ERROR "AOWIS_COVERAGE_BINARY_DIR is required")
endif()

file(GLOB_RECURSE AOWIS_COVERAGE_DATA_FILES
    "${AOWIS_COVERAGE_BINARY_DIR}/*.gcda"
)
if(AOWIS_COVERAGE_DATA_FILES)
    file(REMOVE ${AOWIS_COVERAGE_DATA_FILES})
endif()
