cmake_minimum_required(VERSION 3.21)

foreach(AOWIS_REQUIRED_VARIABLE IN ITEMS
    AOWIS_UPSTREAM_SOURCE_DIR
    AOWIS_UPSTREAM_BINARY_DIR
    AOWIS_UPSTREAM_GENERATOR
)
    if(NOT DEFINED ${AOWIS_REQUIRED_VARIABLE} OR "${${AOWIS_REQUIRED_VARIABLE}}" STREQUAL "")
        message(FATAL_ERROR "Missing required variable: ${AOWIS_REQUIRED_VARIABLE}")
    endif()
endforeach()

set(AOWIS_CONFIGURE_COMMAND
    "${CMAKE_COMMAND}"
    -S "${AOWIS_UPSTREAM_SOURCE_DIR}"
    -B "${AOWIS_UPSTREAM_BINARY_DIR}"
    -G "${AOWIS_UPSTREAM_GENERATOR}"
    -DBUILD_TESTS=ON
    -DBUILD_COVERAGE=OFF
    -DBUILD_SHARED_LIBS=ON
)

if(DEFINED AOWIS_UPSTREAM_BUILD_TYPE AND NOT "${AOWIS_UPSTREAM_BUILD_TYPE}" STREQUAL "")
    list(APPEND AOWIS_CONFIGURE_COMMAND "-DCMAKE_BUILD_TYPE=${AOWIS_UPSTREAM_BUILD_TYPE}")
endif()
if(DEFINED AOWIS_UPSTREAM_C_COMPILER AND NOT "${AOWIS_UPSTREAM_C_COMPILER}" STREQUAL "")
    list(APPEND AOWIS_CONFIGURE_COMMAND "-DCMAKE_C_COMPILER=${AOWIS_UPSTREAM_C_COMPILER}")
endif()
if(DEFINED AOWIS_UPSTREAM_CXX_COMPILER AND NOT "${AOWIS_UPSTREAM_CXX_COMPILER}" STREQUAL "")
    list(APPEND AOWIS_CONFIGURE_COMMAND "-DCMAKE_CXX_COMPILER=${AOWIS_UPSTREAM_CXX_COMPILER}")
endif()
if(DEFINED AOWIS_UPSTREAM_MAKE_PROGRAM AND NOT "${AOWIS_UPSTREAM_MAKE_PROGRAM}" STREQUAL "")
    list(APPEND AOWIS_CONFIGURE_COMMAND "-DCMAKE_MAKE_PROGRAM=${AOWIS_UPSTREAM_MAKE_PROGRAM}")
endif()

execute_process(
    COMMAND ${AOWIS_CONFIGURE_COMMAND}
    RESULT_VARIABLE AOWIS_CONFIGURE_RESULT
    COMMAND_ECHO STDOUT
)
if(NOT AOWIS_CONFIGURE_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to configure the original EPANET Boost suite")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" --build "${AOWIS_UPSTREAM_BINARY_DIR}" --parallel
    RESULT_VARIABLE AOWIS_BUILD_RESULT
    COMMAND_ECHO STDOUT
)
if(NOT AOWIS_BUILD_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to build the original EPANET Boost suite")
endif()

execute_process(
    COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${AOWIS_UPSTREAM_BINARY_DIR}" --output-on-failure
    RESULT_VARIABLE AOWIS_CTEST_RESULT
    COMMAND_ECHO STDOUT
)
if(NOT AOWIS_CTEST_RESULT EQUAL 0)
    message(FATAL_ERROR "The original EPANET CTest suite failed")
endif()

set(AOWIS_CSTRHELPER_EXECUTABLE "${AOWIS_UPSTREAM_BINARY_DIR}/bin/test_cstrhelper${AOWIS_UPSTREAM_EXECUTABLE_SUFFIX}")
if(NOT EXISTS "${AOWIS_CSTRHELPER_EXECUTABLE}")
    message(FATAL_ERROR "Upstream test_cstrhelper executable was not produced")
endif()

execute_process(
    COMMAND "${AOWIS_CSTRHELPER_EXECUTABLE}"
    RESULT_VARIABLE AOWIS_CSTRHELPER_RESULT
    COMMAND_ECHO STDOUT
)
if(NOT AOWIS_CSTRHELPER_RESULT EQUAL 0)
    message(FATAL_ERROR "The upstream test_cstrhelper Boost executable failed")
endif()
